### PR TITLE
Fix: Combine tags correctly when transforming story files

### LINKED ISSUE #484: [Bug]: --includeTags missing some tests
### Describe the bug

I'm using --includeTags to filter components tagged with 'component'. While the tests are running, it says '24 passed', but when it completes it changes to '13 passed', and ignores some of the component stories. I've tried checking the stories to see if there are any obvious differences but I cant see any. I've included examples below.

### To Reproduce

run :test-storybook --includeTags=\"component\" --coverage --coverageDirectory sb-coverage

this story runs:
```js
import React from 'react';
import { userEvent, within, expect, fn } from '@storybook/test';
import CancelButton from './CancelButton';

export default {
  title: 'Components/CancelButton',
  tags: ['component'],
  component: CancelButton,
};

export const Default = {};

export const Test = {
  args: {
    onClick: fn(),
    onClickData: { test: 'test' },
  },
  play: async ({ args, canvasElement }) => {
    const canvas = within(canvasElement);
    await userEvent.click(canvas.getByRole('button'));
    await expect(args.onClick).toHaveBeenCalledWith({ test: 'test' });
  },
};
```
this story is ignored:
```js
import React from 'react';
import { within, expect, fn, userEvent } from '@storybook/test';
import Checkbox from './Checkbox';

export default {
  title: 'Components/Checkbox',
  component: Checkbox,
  tags: ['component'],
  args: {
    onChange: fn(),
    defaultValue: false,
    label: 'Send me news',
    value: false,
    formState: {
      checkbox: {
        value: {
          checkbox: false,
        },
      },
    },
    componentName: 'checkbox',
  },
};

export const Default = {
  play: async ({ args, canvasElement }) => {
    const canvas = within(canvasElement);
    const checkbox = canvas.getByRole('checkbox');
    expect(checkbox).toBeInTheDocument();
    userEvent.click(checkbox);
    // await waitFor(() => expect(checkbox).toBeChecked());
    // expect(args.onChange).toHaveBeenCalledWith({ value: { checkbox: true } });
  },
};
```

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (24) x64 AMD Ryzen 9 7900X 12-Core Processor
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.13.0 - ~/.nvm/versions/node/v20.13.0/bin/node
    Yarn: 1.22.22 - ~/mason-web/node_modules/.bin/yarn <----- active
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.0/bin/npm
  npmPackages:
    @storybook/addon-actions: ^8.1.9 => 8.1.9
    @storybook/addon-controls: ^8.1.9 => 8.1.9
    @storybook/addon-coverage: ^1.0.4 => 1.0.4
    @storybook/addon-designs: ^8.0.2 => 8.0.2
    @storybook/addon-essentials: ^8.1.9 => 8.1.9
    @storybook/addon-interactions: ^8.1.9 => 8.1.9
    @storybook/addon-links: ^8.1.9 => 8.1.9
    @storybook/addon-mdx-gfm: ^8.1.9 => 8.1.9
    @storybook/addon-storysource: ^8.1.9 => 8.1.9
    @storybook/addon-viewport: ^8.1.9 => 8.1.9
    @storybook/addon-webpack5-compiler-babel: ^3.0.3 => 3.0.3
    @storybook/manager-api: ^8.1.9 => 8.1.9
    @storybook/react: ^8.1.9 => 8.1.9
    @storybook/react-webpack5: ^8.1.9 => 8.1.9
    @storybook/source-loader: ^8.1.9 => 8.1.9
    @storybook/test: ^8.1.9 => 8.1.9
    @storybook/test-runner: ^0.18.2 => 0.18.2
    msw-storybook-addon: ^2.0.2 => 2.0.2
    storybook: ^8.1.9 => 8.1.9
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yannbf**
Closes #484

## What I did

This PR fixes the issue with tag filtering inconsistency between non-index-json mode and index-json mode.
Additionally, it adds a default include filter for stories tagged as `test`. It has backwards compatibility with older indexes such as v3 and v4.

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes in this repository
- [ ] Request documentation updates in the [test-runner docs website](https://storybook.js.org/docs/writing-tests/test-runner)

## Checklist for Maintainers

- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `skip-release`: Skip any releases, e.g., documentation only changes, CI config etc.
  - `patch`: Upgrade patch version (e.g. 0.0.x)
  - `minor`: Upgrade patch version (e.g. 0.x.0)
  - `major`: Upgrade patch version (e.g. x.0.0)

   </details>

<details>
  <summary>📦 Published PR as canary version: <code>0.18.3--canary.485.a54e616.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @storybook/test-runner@0.18.3--canary.485.a54e616.0
  # or 
  yarn add @storybook/test-runner@0.18.3--canary.485.a54e616.0
  ```
</details>

### CODE REVIEW

File: src/csf/transformCsf.ts [hunk 1]
```diff
@@ -126,7 +127,14 @@ export const transformCsf = (
         acc[key].play = annotations.play;
       }
 
-      acc[key].tags = csf._stories[key].tags || csf.meta?.tags || [];
+      acc[key].tags = combineTags(
+        'test',
+        'dev',
+        ...(csf.meta?.tags || []),
+        ...(csf._stories[key].tags || []),
+        ...previewAnnotations.tags
```
Comment (shilman) [inline src/csf/transformCsf.ts:135]: This needs to move above the meta for tag precedence

**Review by shilman — CHANGES_REQUESTED** [review]
Looks great! Small change requested and you might want to add a test for it too

File: src/csf/transformCsf.ts (hunk 1 above)
Comment (yannbf) [reply src/csf/transformCsf.ts]: Great catch, thanks! Fixed and test written
