### PR TITLE
fix: Support Storybook 6.5

### LINKED ISSUE #106: [Bug] Error "TypeError: (0 , _store.autoTitle) is not a function" when running test-storybook command
### Describe the bug

When running `yarn test-storybook` the following error is reported for each story.

```
 FAIL   browser: chromium  src/stories/Components/Cards/GeneralCard/GeneralCard.stories.tsx
  ● Test suite failed to run                                                                                                                                                 
                                                                                                                                                                             
    TypeError: (0 , _store.autoTitle) is not a function                                                                                                                      
                                                                                                                                                                             
      at getDefaultTitle (node_modules/@storybook/test-runner/dist/cjs/playwright/transformPlaywright.js:72:31)                                                              
      at transformPlaywright (node_modules/@storybook/test-runner/dist/cjs/playwright/transformPlaywright.js:76:24)                                                          
      at Object.process (node_modules/@storybook/test-runner/playwright/transform.js:6:21)                                                                                   
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:619:31)                                                                  
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:765:40)                                                         
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:822:19)
```

### Environment

 - OS: Windows 11
 - Node.js version: 16.13.0
 - NPM version: 8.1.0
 - Browser (if applicable): N/A
 - Browser version (if applicable): N/A
 - Device (if applicable): N/A

### Additional context

This is on an existing storybook that I've upgraded from `@storybook/react@^6.2.9` to `@storybook/react@next`

### PR DESCRIPTION
**Pull request by valentinpalkovic**
[BREAKING CHANGES]: Drop Storybook 6.4 support

fixes #106

<details>
  <summary>📦 Published PR as canary version: <code>0.0.9--canary.107.1f96eca.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @storybook/test-runner@0.0.9--canary.107.1f96eca.0
  # or 
  yarn add @storybook/test-runner@0.0.9--canary.107.1f96eca.0
  ```
</details>

### Breaking change 💥 

This version adds support to Storybook 6.5 and drops support for Storybook 6.4. Unfortunately there was a breaking change in an internal API from `@storybook/store` which is used by the test runner, which **only affects users that use the auto title feature**. 

Changes included from [this pull request](https://github.com/storybookjs/test-runner/pull/107) (#107)

### CODE REVIEW

File: src/playwright/transformPlaywrightJson.ts [hunk 1]
```diff
@@ -43,7 +43,7 @@ export const transformPlaywrightJson = (src: string) => {
   }
   const stories = Object.values(json.stories) as Story[];
   const titleIdToStories = stories.reduce((acc, story) => {
-    const titleId = toId(story.title);
+    const titleId = toId(story.kind, story.story);
```
Comment (shilman) [inline src/playwright/transformPlaywrightJson.ts:46]: why is this change needed? also `kind/story` are deprecated and `title/name` should be used instead. but i don't know why we need this change to begin with.

File: src/playwright/transformPlaywrightJson.ts [hunk 2]
```diff
@@ -4,7 +4,7 @@ import { toId } from '@storybook/csf';
 
 import { testPrefixer } from './transformPlaywright';
 
-type Story = { id: string; name: string; title: string; parameters?: Record<string, any> };
+type Story = { id: string; name: string; title: string; parameters?: Record<string, any>, kind: string, story: string };
```
Comment (shilman) [inline src/playwright/transformPlaywrightJson.ts:7]: kind/story are deprecated and shouldn't be used

File: package.json [hunk 3]
```diff
@@ -109,9 +109,9 @@
     "ts-dedent": "^2.0.0"
   },
   "peerDependencies": {
-    "@storybook/core-common": "^6.4.0 || >= 6.5.0-alpha.1",
-    "@storybook/csf-tools": "^6.4.0 || >= 6.5.0-alpha.1",
-    "@storybook/store": "^6.4.0 || >= 6.5.0-alpha.1",
+    "@storybook/core-common": ">= 6.5.0-rc.0",
```
Comment (shilman) [inline package.json:112]: probably just `^6.5.0` now that it's live?

File: package.json [hunk 4]
```diff
@@ -97,7 +97,7 @@
     "icon": "https://user-images.githubusercontent.com/321738/63501763-88dbf600-c4cc-11e9-96cd-94adadc2fd72.png"
   },
   "dependencies": {
-    "@storybook/csf": "0.0.2--canary.87bc651.0",
+    "@storybook/csf": "0.0.2-alpha.0",
```
Comment (shilman) [inline package.json:100]: I think we should use the same canary as the storybook monorepo. I promise I'll clean this up later this week

**Review by shilman — CHANGES_REQUESTED** [review]
Bunch of stuff, but the `makeTitle` stuff is super urgent. Thanks so much for catching this @valentinpalkovic and for the quick PR

File: package.json (hunk 4 above)
Comment (yannbf) [reply package.json]: done

File: package.json (hunk 3 above)
Comment (yannbf) [reply package.json]: done

File: src/playwright/transformPlaywrightJson.ts (hunk 1 above)
Comment (yannbf) [reply src/playwright/transformPlaywrightJson.ts:46]: This seems to be necessary. Another working version of the code is `toId(story.title, story.name)`. 

```ts
// With SB 6.5 and this code: toId(story.title) 
{ titleId: 'atoms-button' } // Wrong!

// With SB 6.5 and toId(story.kind, story.story) || toId(story.title, story.name)
{ titleId: 'atoms-button--wait-for' } // Correct!
```

File: src/playwright/transformPlaywrightJson.ts (hunk 2 above)
Comment (valentinpalkovic) [reply src/playwright/transformPlaywrightJson.ts]: replaced by `story.title` and `story.name`

File: src/playwright/transformPlaywrightJson.ts (hunk 1 above)
Comment (valentinpalkovic) [reply src/playwright/transformPlaywrightJson.ts]: Done. Replaced by `story.title` and `story.name`

File: src/playwright/transformPlaywrightJson.ts [hunk 5]
```diff
@@ -43,7 +43,7 @@ export const transformPlaywrightJson = (src: string) => {
   }
   const stories = Object.values(json.stories) as Story[];
   const titleIdToStories = stories.reduce((acc, story) => {
-    const titleId = toId(story.title);
+    const titleId = toId(story.title, story.name);
```
Comment (yannbf) [inline src/playwright/transformPlaywrightJson.ts:46]: After giving a bit more thought I don't think this is right. The idea is to actually group stories per component.
So `toId(story.title)` would generate an id of e.g. `example-page` which would result in an aggregated object like:

```js
{
  "example-page": `
    describe("Example/Page", () => {
      describe("Logged In", () => {
        it("test", async () => {
          // ...
        })
      })
      describe("Logged Out", () => {
        it("test", async () => {
          // ...
        })
      })
    })
  `
}
```


And `toId(story.title, story.name)` would generate the entire title like `example-header--logged-in`, so the aggregation would not be correct, as we'd have a lot of describes with the same name
```js
{
  "example-page--logged-in": `
    describe("Example/Page", () => {
      describe("Logged In", () => {
        it("test", async () => {
          // ...
        })
      })
    })
  `,
  "example-page--logged-out": `
    describe("Example/Page", () => {
      describe("Logged Out", () => {
        it("test", async () => {
          // ...
        })
      })
    })
  `,
}
```

Comment (valentinpalkovic) [reply src/playwright/transformPlaywrightJson.ts]: The newest version of the toID method defines the second parameter as optional (https://github.com/ComponentDriven/csf/blob/b02ef28ede03446514f64dd10085c9cef7de5d7d/src/index.ts#L31) but I cannot find a released version of it

Comment (yannbf) [reply src/playwright/transformPlaywrightJson.ts]: Change is done!
